### ISSUE TITLE
How to extract the learning curve of the mean GP-FNN predictor

### ISSUE THREAD

**Issue by saigontrade88** [lionelmessi6410/ntga#5]
Hello,

Thanks you for sharing your code. I am looking at line 193, in plot_learning_dynamics.py. I want to know how to extract the train accuracy and test accuracy of the mean GP-FNN predictor across time steps. 

Also, I am looking at contour_plot function at line 88 to learn how to use these train and test accuracy arrays. You define them as follows.

 train_acc refers to the training accuracies for different weight variances and time steps.
 test_acc refers to the test accuracies for different weight variances and time steps.

What do you mean by 'weight variances'? I will look into the weight variances for sure but can you give some guidance here just in case I am heading in the wrong direction? Any information is appreciated. Many thanks. 

Long

**Comment by lionelmessi6410** [comment]
Hello, I don’t know if this issue still exists. If so, I would be glad to share more details with you. In the Neural Tangent Kernel theory, different weight variance used at initialization leads to different training and testing accuracy. The contour plot simply visualizes this behavior at the same time. Let me know if you have any other questions.
